webDriver_hw
AlioshynaSasha/TAF pull request #2
Opened 2022-10-08 21:34 UTC by AlioshynaSasha

Testing calculator in http://13gp.by/informatsiya/meditsinskie-kalkulyatory/995-raschet-skorosti-klubochkovoj-filtratsii-skf

2022-10-16 18:20 UTC, wildpioneer requested changes

2022-10-16 18:20 UTC, wildpioneer commented on src/test/java/tests/SmokeTest2.java
> +        WebElement button = driver.findElement(By.cssSelector("#Form1 > ul > li:nth-child(6) > input[type=button]:nth-child(1)"));
Необходимо переделать данный локатор на простой

2022-10-16 18:20 UTC, wildpioneer commented on src/test/java/tests/SmokeTest2.java
> +
А остальные задачи?

2022-10-17 19:42 UTC, AlioshynaSasha commented on src/test/java/tests/SmokeTest2.java
> +        WebElement button = driver.findElement(By.cssSelector("#Form1 > ul > li:nth-child(6) > input[type=button]:nth-child(1)"));
Переделала на более простой

2022-10-17 19:42 UTC, AlioshynaSasha commented on src/test/java/tests/SmokeTest2.java
> +
Добавила

2022-10-30 09:43 UTC, wildpioneer commented
Проверено

2022-10-30 09:43 UTC, closed without merging